name: Gulp and Publish Website

on: 
  push: 
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile with Grunt (Minify and Optimize images)
      uses: elstudio/actions-js-build/build@v2
    # - name: FTP-Deploy-Action
    #   uses: SamKirkland/FTP-Deploy-Action@3.0.0
    #   with:
    #     ftp-server: ftp://<server>
    #     ftp-username: <USER_NAME>
    #     ftp-password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: src
